[package]
name = "cw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
crossbeam-channel = "0.5.8"
crossterm = "0.27.0"
fastrand = "2.0.1"
input = "0.8.3"
ratatui = "0.24.0"
tokio = { version = "1.34.0", features = ["full"] }
